#!/usr/bin/env bash

# AMD Ryzen 7 4800H processor profiler CLI tool for Slimbook computers
# If you use different AND processor, please review the params here https://shorturl.at/jHJ35

COLOR_OFF='\033[0m' # Text Reset
GREEN='\033[0;32m'  # Green
YELLOW='\033[0;33m' # Yellow

CPU=$(cat /proc/cpuinfo | grep name | uniq | cut -d ':' -f2 | sed -r "s/^\s+//g")

help() {
	printf "${YELLOW}Slimbook ${CPU} profile updater tool${COLOR_OFF}\n\n"
	printf "${GREEN}Usage amd-controller [command <option>] [option]${COLOR_OFF}\n\n"
	printf "${YELLOW}Commands:${COLOR_OFF}"
	echo "set <option>       Set processor profile"
	echo
	printf "${YELLOW}Options:${COLOR_OFF}\n"
	echo "-b, --base         Set your processor to work with a base profile"
	echo "-s, --slow         Set your processor to work with a slow profile"
	echo "-m, --medium       Set your processor to work with a medium profile"
	echo "-hi, --high        Set your processor to work with a high profil"
	echo
	printf "${YELLOW}Flags:${COLOR_OFF}\n"
	echo "-h, --help         Show CLI help"
	echo "-i, --ifo          Show processor profile info"
	echo
	printf "${GREEN}Run 'amd-controller set -s' to set your processor to work with a slow profile${COLOR_OFF}\n"
	echo
	echo "Inspirated by: https://shorturl.at/hqrAL"
	echo "Review params for other AMD processors here: https://shorturl.at/jHJ35"
}

check_dependences() {
	if ! command -v ryzenadj &>/dev/null 2>&1; then
		printf >&2 "${RED}Error: ryzenadj could not be found\n"
		exit 1
	fi
}

set_base_profile() {
	sudo ryzenadj --tctl-temp=95 --slow-limit=30000 --stapm-limit=30000 --fast-limit=35000 &>/dev/null
	printf "${GREEN}🛠  BASE profile set successfully for $CPU processor\n"
	notify-send "AMD Controller" "🔔 BASE profile set successfully for ${CPU}" -t 4000
}

set_slow_profile() {
	sudo ryzenadj --tctl-temp=95 --slow-limit=10000 --stapm-limit=10000 --fast-limit=10000 &>/dev/null
	printf "${GREEN}🛠  SLOW profile set successfully for $CPU processor\n"
	notify-send "AMD Controller" "🔔 SLOW profile set successfully for ${CPU}" -t 4000
}

set_medium_profile() {
	sudo ryzenadj --tctl-temp=95 --slow-limit=15000 --stapm-limit=15000 --fast-limit=25000 &>/dev/null
	printf "${GREEN}🛠  MEDIUM profile set successfully for $CPU processor\n"
	notify-send "AMD Controller" "🔔 MEDIUM profile set successfully for ${CPU}" -t 4000
}

set_high_profile() {
	sudo ryzenadj --tctl-temp=95 --slow-limit=70000 --stapm-limit=80000 --fast-limit=100000 &>/dev/null
	printf "${GREEN}🛠  HIGH profile set successfully for $CPU processor\n"
	notify-send "AMD Controller" "🔔HIGH profile set successfully for ${CPU}" -t 4000
}

show_processor_profile_info() {
	sudo ryzenadj -i
}

check_dependences

case "$1" in
set)
	case $2 in
	-b | --base)
		set_base_profile
		;;
	-s | --slow)
		set_slow_profile
		;;
	-m | --medium)
		set_medium_profile
		;;
	-hi | --high)
		set_high_profile
		;;
	-h | --help)
		help
		;;
	*)
		printf "${YELLOW}Invalid option\n${COLOR_OFF}"
		help
		;;
	esac
	;;
-i | --info)
	show_processor_profile_info
	;;
-h | --help)
	help
	;;
*)
	printf "${YELLOW}Invalid command or option\n${COLOR_OFF}"
	help
	;;
esac
